package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
)

// CatalogsGetURL generates an URL for the catalogs get operation
type CatalogsGetURL struct {
	Query *string
	Sort  *string

	// avoid unkeyed usage
	_ struct{}
}

// Build a url path and query string
func (o *CatalogsGetURL) Build() (*url.URL, error) {
	var result url.URL

	var _path = "/catalogs"

	result.Path = _path

	qs := make(url.Values)

	var query string
	if o.Query != nil {
		query = *o.Query
	}
	if query != "" {
		qs.Set("query", query)
	}

	var sort string
	if o.Sort != nil {
		sort = *o.Sort
	}
	if sort != "" {
		qs.Set("sort", sort)
	}

	result.RawQuery = qs.Encode()

	return &result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *CatalogsGetURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *CatalogsGetURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *CatalogsGetURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on CatalogsGetURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on CatalogsGetURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *CatalogsGetURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
