package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	context "golang.org/x/net/context"

	middleware "github.com/go-openapi/runtime/middleware"
)

// CatalogsGetHandlerFunc turns a function with the right signature into a catalogs get handler
type CatalogsGetHandlerFunc func(context.Context, CatalogsGetParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CatalogsGetHandlerFunc) Handle(ctx context.Context, params CatalogsGetParams) middleware.Responder {
	return fn(ctx, params)
}

// CatalogsGetHandler interface for that can handle valid catalogs get params
type CatalogsGetHandler interface {
	Handle(context.Context, CatalogsGetParams) middleware.Responder
}

// NewCatalogsGet creates a new http.Handler for the catalogs get operation
func NewCatalogsGet(ctx *middleware.Context, handler CatalogsGetHandler) *CatalogsGet {
	return &CatalogsGet{Context: ctx, Handler: handler}
}

/*CatalogsGet swagger:route GET /catalogs /api/2.0 catalogsGet

Get all catalogs

Get an array of catalog data describing all hardware in the system.

*/
type CatalogsGet struct {
	Context *middleware.Context
	Handler CatalogsGetHandler
}

func (o *CatalogsGet) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewCatalogsGetParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(context.Background(), Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
