package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	"strings"
)

// FilesMetadataGetURL generates an URL for the files metadata get operation
type FilesMetadataGetURL struct {
	Filename string

	// avoid unkeyed usage
	_ struct{}
}

// Build a url path and query string
func (o *FilesMetadataGetURL) Build() (*url.URL, error) {
	var result url.URL

	var _path = "/files/{filename}/metadata"

	filename := o.Filename
	if filename != "" {
		_path = strings.Replace(_path, "{filename}", filename, -1)
	} else {
		return nil, errors.New("Filename is required on FilesMetadataGetURL")
	}
	result.Path = _path

	return &result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *FilesMetadataGetURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *FilesMetadataGetURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *FilesMetadataGetURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on FilesMetadataGetURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on FilesMetadataGetURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *FilesMetadataGetURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
