package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	context "golang.org/x/net/context"

	middleware "github.com/go-openapi/runtime/middleware"
)

// FilesPutHandlerFunc turns a function with the right signature into a files put handler
type FilesPutHandlerFunc func(context.Context, FilesPutParams) middleware.Responder

// Handle executing the request and returning a response
func (fn FilesPutHandlerFunc) Handle(ctx context.Context, params FilesPutParams) middleware.Responder {
	return fn(ctx, params)
}

// FilesPutHandler interface for that can handle valid files put params
type FilesPutHandler interface {
	Handle(context.Context, FilesPutParams) middleware.Responder
}

// NewFilesPut creates a new http.Handler for the files put operation
func NewFilesPut(ctx *middleware.Context, handler FilesPutHandler) *FilesPut {
	return &FilesPut{Context: ctx, Handler: handler}
}

/*FilesPut swagger:route PUT /files/{fileidentifier} /api/2.0 filesPut

Put a file

Put file based on its filename. Returns the uuid of the stored file.

*/
type FilesPut struct {
	Context *middleware.Context
	Handler FilesPutHandler
}

func (o *FilesPut) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewFilesPutParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(context.Background(), Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
