package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/RackHD/neighborhood-manager/rackhd/api/swagger/models"
)

/*GetBootstrapOK Successfully retrieved bootstrap.js

swagger:response getBootstrapOK
*/
type GetBootstrapOK struct {

	// In: body
	Payload *models.VersionsResponse `json:"body,omitempty"`
}

// NewGetBootstrapOK creates GetBootstrapOK with default headers values
func NewGetBootstrapOK() *GetBootstrapOK {
	return &GetBootstrapOK{}
}

// WithPayload adds the payload to the get bootstrap o k response
func (o *GetBootstrapOK) WithPayload(payload *models.VersionsResponse) *GetBootstrapOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get bootstrap o k response
func (o *GetBootstrapOK) SetPayload(payload *models.VersionsResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBootstrapOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetBootstrapDefault Error

swagger:response getBootstrapDefault
*/
type GetBootstrapDefault struct {
	_statusCode int

	// In: body
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewGetBootstrapDefault creates GetBootstrapDefault with default headers values
func NewGetBootstrapDefault(code int) *GetBootstrapDefault {
	if code <= 0 {
		code = 500
	}

	return &GetBootstrapDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get bootstrap default response
func (o *GetBootstrapDefault) WithStatusCode(code int) *GetBootstrapDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get bootstrap default response
func (o *GetBootstrapDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get bootstrap default response
func (o *GetBootstrapDefault) WithPayload(payload *models.ErrorResponse) *GetBootstrapDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get bootstrap default response
func (o *GetBootstrapDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBootstrapDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
