package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/RackHD/neighborhood-manager/rackhd/api/swagger/models"
)

/*GetNodesByTagOK Successfully retrieved the list of nodes with the specified tag

swagger:response getNodesByTagOK
*/
type GetNodesByTagOK struct {

	// In: body
	Payload []interface{} `json:"body,omitempty"`
}

// NewGetNodesByTagOK creates GetNodesByTagOK with default headers values
func NewGetNodesByTagOK() *GetNodesByTagOK {
	return &GetNodesByTagOK{}
}

// WithPayload adds the payload to the get nodes by tag o k response
func (o *GetNodesByTagOK) WithPayload(payload []interface{}) *GetNodesByTagOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get nodes by tag o k response
func (o *GetNodesByTagOK) SetPayload(payload []interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetNodesByTagOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*GetNodesByTagNotFound The specified tag was not found

swagger:response getNodesByTagNotFound
*/
type GetNodesByTagNotFound struct {

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetNodesByTagNotFound creates GetNodesByTagNotFound with default headers values
func NewGetNodesByTagNotFound() *GetNodesByTagNotFound {
	return &GetNodesByTagNotFound{}
}

// WithPayload adds the payload to the get nodes by tag not found response
func (o *GetNodesByTagNotFound) WithPayload(payload *models.Error) *GetNodesByTagNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get nodes by tag not found response
func (o *GetNodesByTagNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetNodesByTagNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetNodesByTagDefault Unexpected error

swagger:response getNodesByTagDefault
*/
type GetNodesByTagDefault struct {
	_statusCode int

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetNodesByTagDefault creates GetNodesByTagDefault with default headers values
func NewGetNodesByTagDefault(code int) *GetNodesByTagDefault {
	if code <= 0 {
		code = 500
	}

	return &GetNodesByTagDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get nodes by tag default response
func (o *GetNodesByTagDefault) WithStatusCode(code int) *GetNodesByTagDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get nodes by tag default response
func (o *GetNodesByTagDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get nodes by tag default response
func (o *GetNodesByTagDefault) WithPayload(payload *models.Error) *GetNodesByTagDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get nodes by tag default response
func (o *GetNodesByTagDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetNodesByTagDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
