package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	context "golang.org/x/net/context"

	middleware "github.com/go-openapi/runtime/middleware"
)

// NodesAddRelationsHandlerFunc turns a function with the right signature into a nodes add relations handler
type NodesAddRelationsHandlerFunc func(context.Context, NodesAddRelationsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NodesAddRelationsHandlerFunc) Handle(ctx context.Context, params NodesAddRelationsParams) middleware.Responder {
	return fn(ctx, params)
}

// NodesAddRelationsHandler interface for that can handle valid nodes add relations params
type NodesAddRelationsHandler interface {
	Handle(context.Context, NodesAddRelationsParams) middleware.Responder
}

// NewNodesAddRelations creates a new http.Handler for the nodes add relations operation
func NewNodesAddRelations(ctx *middleware.Context, handler NodesAddRelationsHandler) *NodesAddRelations {
	return &NodesAddRelations{Context: ctx, Handler: handler}
}

/*NodesAddRelations swagger:route PUT /nodes/{identifier}/relations /api/2.0 nodesAddRelations

Add relationships between nodes

Edit the relations fields of a specifc node to add one more relationships.

*/
type NodesAddRelations struct {
	Context *middleware.Context
	Handler NodesAddRelationsHandler
}

func (o *NodesAddRelations) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewNodesAddRelationsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(context.Background(), Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// NodesAddRelationsOKBody nodes add relations o k body
// swagger:model NodesAddRelationsOKBody
type NodesAddRelationsOKBody interface{}
