package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	"strings"
)

// NodesMasterDelTagByIDURL generates an URL for the nodes master del tag by Id operation
type NodesMasterDelTagByIDURL struct {
	TagName string

	// avoid unkeyed usage
	_ struct{}
}

// Build a url path and query string
func (o *NodesMasterDelTagByIDURL) Build() (*url.URL, error) {
	var result url.URL

	var _path = "/nodes/tags/{tagName}"

	tagName := o.TagName
	if tagName != "" {
		_path = strings.Replace(_path, "{tagName}", tagName, -1)
	} else {
		return nil, errors.New("TagName is required on NodesMasterDelTagByIDURL")
	}
	result.Path = _path

	return &result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *NodesMasterDelTagByIDURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *NodesMasterDelTagByIDURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *NodesMasterDelTagByIDURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on NodesMasterDelTagByIDURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on NodesMasterDelTagByIDURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *NodesMasterDelTagByIDURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
