package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	context "golang.org/x/net/context"

	middleware "github.com/go-openapi/runtime/middleware"
)

// NodesGetTagsByIDHandlerFunc turns a function with the right signature into a nodes get tags by Id handler
type NodesGetTagsByIDHandlerFunc func(context.Context, NodesGetTagsByIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NodesGetTagsByIDHandlerFunc) Handle(ctx context.Context, params NodesGetTagsByIDParams) middleware.Responder {
	return fn(ctx, params)
}

// NodesGetTagsByIDHandler interface for that can handle valid nodes get tags by Id params
type NodesGetTagsByIDHandler interface {
	Handle(context.Context, NodesGetTagsByIDParams) middleware.Responder
}

// NewNodesGetTagsByID creates a new http.Handler for the nodes get tags by Id operation
func NewNodesGetTagsByID(ctx *middleware.Context, handler NodesGetTagsByIDHandler) *NodesGetTagsByID {
	return &NodesGetTagsByID{Context: ctx, Handler: handler}
}

/*NodesGetTagsByID swagger:route GET /nodes/{identifier}/tags /api/2.0 nodesGetTagsById

Get node tags

Get a list of all tags associated with the specified node.

*/
type NodesGetTagsByID struct {
	Context *middleware.Context
	Handler NodesGetTagsByIDHandler
}

func (o *NodesGetTagsByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewNodesGetTagsByIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(context.Background(), Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
