package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/RackHD/neighborhood-manager/rackhd/api/swagger/models"
)

/*ObmsDefinitionsGetAllOK Successfully retrieved a list of OBM schemas

swagger:response obmsDefinitionsGetAllOK
*/
type ObmsDefinitionsGetAllOK struct {

	// In: body
	Payload ObmsDefinitionsGetAllOKBody `json:"body,omitempty"`
}

// NewObmsDefinitionsGetAllOK creates ObmsDefinitionsGetAllOK with default headers values
func NewObmsDefinitionsGetAllOK() *ObmsDefinitionsGetAllOK {
	return &ObmsDefinitionsGetAllOK{}
}

// WithPayload adds the payload to the obms definitions get all o k response
func (o *ObmsDefinitionsGetAllOK) WithPayload(payload ObmsDefinitionsGetAllOKBody) *ObmsDefinitionsGetAllOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the obms definitions get all o k response
func (o *ObmsDefinitionsGetAllOK) SetPayload(payload ObmsDefinitionsGetAllOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ObmsDefinitionsGetAllOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*ObmsDefinitionsGetAllDefault Unexpected error

swagger:response obmsDefinitionsGetAllDefault
*/
type ObmsDefinitionsGetAllDefault struct {
	_statusCode int

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewObmsDefinitionsGetAllDefault creates ObmsDefinitionsGetAllDefault with default headers values
func NewObmsDefinitionsGetAllDefault(code int) *ObmsDefinitionsGetAllDefault {
	if code <= 0 {
		code = 500
	}

	return &ObmsDefinitionsGetAllDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the obms definitions get all default response
func (o *ObmsDefinitionsGetAllDefault) WithStatusCode(code int) *ObmsDefinitionsGetAllDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the obms definitions get all default response
func (o *ObmsDefinitionsGetAllDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the obms definitions get all default response
func (o *ObmsDefinitionsGetAllDefault) WithPayload(payload *models.Error) *ObmsDefinitionsGetAllDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the obms definitions get all default response
func (o *ObmsDefinitionsGetAllDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ObmsDefinitionsGetAllDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
