package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/RackHD/neighborhood-manager/rackhd/api/swagger/models"
)

/*ObmsDeleteByIDNoContent Successfully deleted the specified OBM settings

swagger:response obmsDeleteByIdNoContent
*/
type ObmsDeleteByIDNoContent struct {

	// In: body
	Payload ObmsDeleteByIDNoContentBody `json:"body,omitempty"`
}

// NewObmsDeleteByIDNoContent creates ObmsDeleteByIDNoContent with default headers values
func NewObmsDeleteByIDNoContent() *ObmsDeleteByIDNoContent {
	return &ObmsDeleteByIDNoContent{}
}

// WithPayload adds the payload to the obms delete by Id no content response
func (o *ObmsDeleteByIDNoContent) WithPayload(payload ObmsDeleteByIDNoContentBody) *ObmsDeleteByIDNoContent {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the obms delete by Id no content response
func (o *ObmsDeleteByIDNoContent) SetPayload(payload ObmsDeleteByIDNoContentBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ObmsDeleteByIDNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(204)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*ObmsDeleteByIDNotFound The OBM service with the specified identifier was not found

swagger:response obmsDeleteByIdNotFound
*/
type ObmsDeleteByIDNotFound struct {

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewObmsDeleteByIDNotFound creates ObmsDeleteByIDNotFound with default headers values
func NewObmsDeleteByIDNotFound() *ObmsDeleteByIDNotFound {
	return &ObmsDeleteByIDNotFound{}
}

// WithPayload adds the payload to the obms delete by Id not found response
func (o *ObmsDeleteByIDNotFound) WithPayload(payload *models.Error) *ObmsDeleteByIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the obms delete by Id not found response
func (o *ObmsDeleteByIDNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ObmsDeleteByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*ObmsDeleteByIDDefault Unexpected error

swagger:response obmsDeleteByIdDefault
*/
type ObmsDeleteByIDDefault struct {
	_statusCode int

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewObmsDeleteByIDDefault creates ObmsDeleteByIDDefault with default headers values
func NewObmsDeleteByIDDefault(code int) *ObmsDeleteByIDDefault {
	if code <= 0 {
		code = 500
	}

	return &ObmsDeleteByIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the obms delete by Id default response
func (o *ObmsDeleteByIDDefault) WithStatusCode(code int) *ObmsDeleteByIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the obms delete by Id default response
func (o *ObmsDeleteByIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the obms delete by Id default response
func (o *ObmsDeleteByIDDefault) WithPayload(payload *models.Error) *ObmsDeleteByIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the obms delete by Id default response
func (o *ObmsDeleteByIDDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ObmsDeleteByIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
