package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/RackHD/neighborhood-manager/rackhd/api/swagger/models"
)

/*PollersLibByIDGetOK Successful retrieval of the specified poller

swagger:response pollersLibByIdGetOK
*/
type PollersLibByIDGetOK struct {

	// In: body
	Payload PollersLibByIDGetOKBody `json:"body,omitempty"`
}

// NewPollersLibByIDGetOK creates PollersLibByIDGetOK with default headers values
func NewPollersLibByIDGetOK() *PollersLibByIDGetOK {
	return &PollersLibByIDGetOK{}
}

// WithPayload adds the payload to the pollers lib by Id get o k response
func (o *PollersLibByIDGetOK) WithPayload(payload PollersLibByIDGetOKBody) *PollersLibByIDGetOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the pollers lib by Id get o k response
func (o *PollersLibByIDGetOK) SetPayload(payload PollersLibByIDGetOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PollersLibByIDGetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*PollersLibByIDGetNotFound The poller with specified identifier not found

swagger:response pollersLibByIdGetNotFound
*/
type PollersLibByIDGetNotFound struct {

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewPollersLibByIDGetNotFound creates PollersLibByIDGetNotFound with default headers values
func NewPollersLibByIDGetNotFound() *PollersLibByIDGetNotFound {
	return &PollersLibByIDGetNotFound{}
}

// WithPayload adds the payload to the pollers lib by Id get not found response
func (o *PollersLibByIDGetNotFound) WithPayload(payload *models.Error) *PollersLibByIDGetNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the pollers lib by Id get not found response
func (o *PollersLibByIDGetNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PollersLibByIDGetNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PollersLibByIDGetDefault Unexpected error

swagger:response pollersLibByIdGetDefault
*/
type PollersLibByIDGetDefault struct {
	_statusCode int

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewPollersLibByIDGetDefault creates PollersLibByIDGetDefault with default headers values
func NewPollersLibByIDGetDefault(code int) *PollersLibByIDGetDefault {
	if code <= 0 {
		code = 500
	}

	return &PollersLibByIDGetDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the pollers lib by Id get default response
func (o *PollersLibByIDGetDefault) WithStatusCode(code int) *PollersLibByIDGetDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the pollers lib by Id get default response
func (o *PollersLibByIDGetDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the pollers lib by Id get default response
func (o *PollersLibByIDGetDefault) WithPayload(payload *models.Error) *PollersLibByIDGetDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the pollers lib by Id get default response
func (o *PollersLibByIDGetDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PollersLibByIDGetDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
