package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/RackHD/neighborhood-manager/rackhd/api/swagger/models"
)

/*PollersDeleteNoContent Poller was deleted successfully

swagger:response pollersDeleteNoContent
*/
type PollersDeleteNoContent struct {
}

// NewPollersDeleteNoContent creates PollersDeleteNoContent with default headers values
func NewPollersDeleteNoContent() *PollersDeleteNoContent {
	return &PollersDeleteNoContent{}
}

// WriteResponse to the client
func (o *PollersDeleteNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(204)
}

/*PollersDeleteNotFound Poller with specified identifier was not found

swagger:response pollersDeleteNotFound
*/
type PollersDeleteNotFound struct {

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewPollersDeleteNotFound creates PollersDeleteNotFound with default headers values
func NewPollersDeleteNotFound() *PollersDeleteNotFound {
	return &PollersDeleteNotFound{}
}

// WithPayload adds the payload to the pollers delete not found response
func (o *PollersDeleteNotFound) WithPayload(payload *models.Error) *PollersDeleteNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the pollers delete not found response
func (o *PollersDeleteNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PollersDeleteNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PollersDeleteDefault Unexpected error

swagger:response pollersDeleteDefault
*/
type PollersDeleteDefault struct {
	_statusCode int

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewPollersDeleteDefault creates PollersDeleteDefault with default headers values
func NewPollersDeleteDefault(code int) *PollersDeleteDefault {
	if code <= 0 {
		code = 500
	}

	return &PollersDeleteDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the pollers delete default response
func (o *PollersDeleteDefault) WithStatusCode(code int) *PollersDeleteDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the pollers delete default response
func (o *PollersDeleteDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the pollers delete default response
func (o *PollersDeleteDefault) WithPayload(payload *models.Error) *PollersDeleteDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the pollers delete default response
func (o *PollersDeleteDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PollersDeleteDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
