package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/RackHD/neighborhood-manager/rackhd/api/swagger/models"
)

/*PollersLibGetOK Successful retrieval of the list of all pollers in the library

swagger:response pollersLibGetOK
*/
type PollersLibGetOK struct {

	// In: body
	Payload PollersLibGetOKBody `json:"body,omitempty"`
}

// NewPollersLibGetOK creates PollersLibGetOK with default headers values
func NewPollersLibGetOK() *PollersLibGetOK {
	return &PollersLibGetOK{}
}

// WithPayload adds the payload to the pollers lib get o k response
func (o *PollersLibGetOK) WithPayload(payload PollersLibGetOKBody) *PollersLibGetOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the pollers lib get o k response
func (o *PollersLibGetOK) SetPayload(payload PollersLibGetOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PollersLibGetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*PollersLibGetDefault Unexpected error

swagger:response pollersLibGetDefault
*/
type PollersLibGetDefault struct {
	_statusCode int

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewPollersLibGetDefault creates PollersLibGetDefault with default headers values
func NewPollersLibGetDefault(code int) *PollersLibGetDefault {
	if code <= 0 {
		code = 500
	}

	return &PollersLibGetDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the pollers lib get default response
func (o *PollersLibGetDefault) WithStatusCode(code int) *PollersLibGetDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the pollers lib get default response
func (o *PollersLibGetDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the pollers lib get default response
func (o *PollersLibGetDefault) WithPayload(payload *models.Error) *PollersLibGetDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the pollers lib get default response
func (o *PollersLibGetDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PollersLibGetDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
