package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/RackHD/neighborhood-manager/rackhd/api/swagger/models"
)

/*PollersIDGetOK Poller information retrieved successfully

swagger:response pollersIdGetOK
*/
type PollersIDGetOK struct {

	// In: body
	Payload PollersIDGetOKBody `json:"body,omitempty"`
}

// NewPollersIDGetOK creates PollersIDGetOK with default headers values
func NewPollersIDGetOK() *PollersIDGetOK {
	return &PollersIDGetOK{}
}

// WithPayload adds the payload to the pollers Id get o k response
func (o *PollersIDGetOK) WithPayload(payload PollersIDGetOKBody) *PollersIDGetOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the pollers Id get o k response
func (o *PollersIDGetOK) SetPayload(payload PollersIDGetOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PollersIDGetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*PollersIDGetNotFound Poller with specified identifier was not found

swagger:response pollersIdGetNotFound
*/
type PollersIDGetNotFound struct {

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewPollersIDGetNotFound creates PollersIDGetNotFound with default headers values
func NewPollersIDGetNotFound() *PollersIDGetNotFound {
	return &PollersIDGetNotFound{}
}

// WithPayload adds the payload to the pollers Id get not found response
func (o *PollersIDGetNotFound) WithPayload(payload *models.Error) *PollersIDGetNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the pollers Id get not found response
func (o *PollersIDGetNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PollersIDGetNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PollersIDGetDefault Unexpected error

swagger:response pollersIdGetDefault
*/
type PollersIDGetDefault struct {
	_statusCode int

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewPollersIDGetDefault creates PollersIDGetDefault with default headers values
func NewPollersIDGetDefault(code int) *PollersIDGetDefault {
	if code <= 0 {
		code = 500
	}

	return &PollersIDGetDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the pollers Id get default response
func (o *PollersIDGetDefault) WithStatusCode(code int) *PollersIDGetDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the pollers Id get default response
func (o *PollersIDGetDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the pollers Id get default response
func (o *PollersIDGetDefault) WithPayload(payload *models.Error) *PollersIDGetDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the pollers Id get default response
func (o *PollersIDGetDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PollersIDGetDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
