package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/RackHD/neighborhood-manager/rackhd/api/swagger/models"
)

/*PollersCurrentDataGetOK Successfully retrieved the latest poller data

swagger:response pollersCurrentDataGetOK
*/
type PollersCurrentDataGetOK struct {

	// In: body
	Payload PollersCurrentDataGetOKBody `json:"body,omitempty"`
}

// NewPollersCurrentDataGetOK creates PollersCurrentDataGetOK with default headers values
func NewPollersCurrentDataGetOK() *PollersCurrentDataGetOK {
	return &PollersCurrentDataGetOK{}
}

// WithPayload adds the payload to the pollers current data get o k response
func (o *PollersCurrentDataGetOK) WithPayload(payload PollersCurrentDataGetOKBody) *PollersCurrentDataGetOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the pollers current data get o k response
func (o *PollersCurrentDataGetOK) SetPayload(payload PollersCurrentDataGetOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PollersCurrentDataGetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*PollersCurrentDataGetNoContent Successfully processed the request and did not return any data

swagger:response pollersCurrentDataGetNoContent
*/
type PollersCurrentDataGetNoContent struct {

	// In: body
	Payload PollersCurrentDataGetNoContentBody `json:"body,omitempty"`
}

// NewPollersCurrentDataGetNoContent creates PollersCurrentDataGetNoContent with default headers values
func NewPollersCurrentDataGetNoContent() *PollersCurrentDataGetNoContent {
	return &PollersCurrentDataGetNoContent{}
}

// WithPayload adds the payload to the pollers current data get no content response
func (o *PollersCurrentDataGetNoContent) WithPayload(payload PollersCurrentDataGetNoContentBody) *PollersCurrentDataGetNoContent {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the pollers current data get no content response
func (o *PollersCurrentDataGetNoContent) SetPayload(payload PollersCurrentDataGetNoContentBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PollersCurrentDataGetNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(204)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*PollersCurrentDataGetNotFound Poller with specified identifier was not found

swagger:response pollersCurrentDataGetNotFound
*/
type PollersCurrentDataGetNotFound struct {

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewPollersCurrentDataGetNotFound creates PollersCurrentDataGetNotFound with default headers values
func NewPollersCurrentDataGetNotFound() *PollersCurrentDataGetNotFound {
	return &PollersCurrentDataGetNotFound{}
}

// WithPayload adds the payload to the pollers current data get not found response
func (o *PollersCurrentDataGetNotFound) WithPayload(payload *models.Error) *PollersCurrentDataGetNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the pollers current data get not found response
func (o *PollersCurrentDataGetNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PollersCurrentDataGetNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PollersCurrentDataGetDefault Unexpected error

swagger:response pollersCurrentDataGetDefault
*/
type PollersCurrentDataGetDefault struct {
	_statusCode int

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewPollersCurrentDataGetDefault creates PollersCurrentDataGetDefault with default headers values
func NewPollersCurrentDataGetDefault(code int) *PollersCurrentDataGetDefault {
	if code <= 0 {
		code = 500
	}

	return &PollersCurrentDataGetDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the pollers current data get default response
func (o *PollersCurrentDataGetDefault) WithStatusCode(code int) *PollersCurrentDataGetDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the pollers current data get default response
func (o *PollersCurrentDataGetDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the pollers current data get default response
func (o *PollersCurrentDataGetDefault) WithPayload(payload *models.Error) *PollersCurrentDataGetDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the pollers current data get default response
func (o *PollersCurrentDataGetDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PollersCurrentDataGetDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
