package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/RackHD/neighborhood-manager/rackhd/api/swagger/models"
)

/*SkusIDGetNodesOK Successfully retrieved the nodes associated with the specified SKU

swagger:response skusIdGetNodesOK
*/
type SkusIDGetNodesOK struct {

	// In: body
	Payload SkusIDGetNodesOKBody `json:"body,omitempty"`
}

// NewSkusIDGetNodesOK creates SkusIDGetNodesOK with default headers values
func NewSkusIDGetNodesOK() *SkusIDGetNodesOK {
	return &SkusIDGetNodesOK{}
}

// WithPayload adds the payload to the skus Id get nodes o k response
func (o *SkusIDGetNodesOK) WithPayload(payload SkusIDGetNodesOKBody) *SkusIDGetNodesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the skus Id get nodes o k response
func (o *SkusIDGetNodesOK) SetPayload(payload SkusIDGetNodesOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SkusIDGetNodesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*SkusIDGetNodesNotFound The SKU with the specified identifier was not found

swagger:response skusIdGetNodesNotFound
*/
type SkusIDGetNodesNotFound struct {

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewSkusIDGetNodesNotFound creates SkusIDGetNodesNotFound with default headers values
func NewSkusIDGetNodesNotFound() *SkusIDGetNodesNotFound {
	return &SkusIDGetNodesNotFound{}
}

// WithPayload adds the payload to the skus Id get nodes not found response
func (o *SkusIDGetNodesNotFound) WithPayload(payload *models.Error) *SkusIDGetNodesNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the skus Id get nodes not found response
func (o *SkusIDGetNodesNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SkusIDGetNodesNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*SkusIDGetNodesDefault Unexpected error

swagger:response skusIdGetNodesDefault
*/
type SkusIDGetNodesDefault struct {
	_statusCode int

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewSkusIDGetNodesDefault creates SkusIDGetNodesDefault with default headers values
func NewSkusIDGetNodesDefault(code int) *SkusIDGetNodesDefault {
	if code <= 0 {
		code = 500
	}

	return &SkusIDGetNodesDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the skus Id get nodes default response
func (o *SkusIDGetNodesDefault) WithStatusCode(code int) *SkusIDGetNodesDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the skus Id get nodes default response
func (o *SkusIDGetNodesDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the skus Id get nodes default response
func (o *SkusIDGetNodesDefault) WithPayload(payload *models.Error) *SkusIDGetNodesDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the skus Id get nodes default response
func (o *SkusIDGetNodesDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SkusIDGetNodesDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
