package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	"strings"
)

// TemplatesLibDeleteURL generates an URL for the templates lib delete operation
type TemplatesLibDeleteURL struct {
	Name string

	Scope *string

	// avoid unkeyed usage
	_ struct{}
}

// Build a url path and query string
func (o *TemplatesLibDeleteURL) Build() (*url.URL, error) {
	var result url.URL

	var _path = "/templates/library/{name}"

	name := o.Name
	if name != "" {
		_path = strings.Replace(_path, "{name}", name, -1)
	} else {
		return nil, errors.New("Name is required on TemplatesLibDeleteURL")
	}
	result.Path = _path

	qs := make(url.Values)

	var scope string
	if o.Scope != nil {
		scope = *o.Scope
	}
	if scope != "" {
		qs.Set("scope", scope)
	}

	result.RawQuery = qs.Encode()

	return &result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *TemplatesLibDeleteURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *TemplatesLibDeleteURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *TemplatesLibDeleteURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on TemplatesLibDeleteURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on TemplatesLibDeleteURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *TemplatesLibDeleteURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
