package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/RackHD/neighborhood-manager/rackhd/api/swagger/models"
)

/*TemplatesLibDeleteNoContent Successfully deleted the specified template

swagger:response templatesLibDeleteNoContent
*/
type TemplatesLibDeleteNoContent struct {
}

// NewTemplatesLibDeleteNoContent creates TemplatesLibDeleteNoContent with default headers values
func NewTemplatesLibDeleteNoContent() *TemplatesLibDeleteNoContent {
	return &TemplatesLibDeleteNoContent{}
}

// WriteResponse to the client
func (o *TemplatesLibDeleteNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(204)
}

/*TemplatesLibDeleteNotFound The template with specified identifier was not found

swagger:response templatesLibDeleteNotFound
*/
type TemplatesLibDeleteNotFound struct {

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewTemplatesLibDeleteNotFound creates TemplatesLibDeleteNotFound with default headers values
func NewTemplatesLibDeleteNotFound() *TemplatesLibDeleteNotFound {
	return &TemplatesLibDeleteNotFound{}
}

// WithPayload adds the payload to the templates lib delete not found response
func (o *TemplatesLibDeleteNotFound) WithPayload(payload *models.Error) *TemplatesLibDeleteNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the templates lib delete not found response
func (o *TemplatesLibDeleteNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *TemplatesLibDeleteNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*TemplatesLibDeleteDefault Unexpected error

swagger:response templatesLibDeleteDefault
*/
type TemplatesLibDeleteDefault struct {
	_statusCode int

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewTemplatesLibDeleteDefault creates TemplatesLibDeleteDefault with default headers values
func NewTemplatesLibDeleteDefault(code int) *TemplatesLibDeleteDefault {
	if code <= 0 {
		code = 500
	}

	return &TemplatesLibDeleteDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the templates lib delete default response
func (o *TemplatesLibDeleteDefault) WithStatusCode(code int) *TemplatesLibDeleteDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the templates lib delete default response
func (o *TemplatesLibDeleteDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the templates lib delete default response
func (o *TemplatesLibDeleteDefault) WithPayload(payload *models.Error) *TemplatesLibDeleteDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the templates lib delete default response
func (o *TemplatesLibDeleteDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *TemplatesLibDeleteDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
