package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/RackHD/neighborhood-manager/rackhd/api/swagger/models"
)

/*TemplatesGetByNameOK Successfuly retrieved the specified template

swagger:response templatesGetByNameOK
*/
type TemplatesGetByNameOK struct {

	// In: body
	Payload TemplatesGetByNameOKBody `json:"body,omitempty"`
}

// NewTemplatesGetByNameOK creates TemplatesGetByNameOK with default headers values
func NewTemplatesGetByNameOK() *TemplatesGetByNameOK {
	return &TemplatesGetByNameOK{}
}

// WithPayload adds the payload to the templates get by name o k response
func (o *TemplatesGetByNameOK) WithPayload(payload TemplatesGetByNameOKBody) *TemplatesGetByNameOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the templates get by name o k response
func (o *TemplatesGetByNameOK) SetPayload(payload TemplatesGetByNameOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *TemplatesGetByNameOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*TemplatesGetByNameNotFound The template with specified identifier was not found

swagger:response templatesGetByNameNotFound
*/
type TemplatesGetByNameNotFound struct {

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewTemplatesGetByNameNotFound creates TemplatesGetByNameNotFound with default headers values
func NewTemplatesGetByNameNotFound() *TemplatesGetByNameNotFound {
	return &TemplatesGetByNameNotFound{}
}

// WithPayload adds the payload to the templates get by name not found response
func (o *TemplatesGetByNameNotFound) WithPayload(payload *models.Error) *TemplatesGetByNameNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the templates get by name not found response
func (o *TemplatesGetByNameNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *TemplatesGetByNameNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*TemplatesGetByNameDefault Unexpected error

swagger:response templatesGetByNameDefault
*/
type TemplatesGetByNameDefault struct {
	_statusCode int

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewTemplatesGetByNameDefault creates TemplatesGetByNameDefault with default headers values
func NewTemplatesGetByNameDefault(code int) *TemplatesGetByNameDefault {
	if code <= 0 {
		code = 500
	}

	return &TemplatesGetByNameDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the templates get by name default response
func (o *TemplatesGetByNameDefault) WithStatusCode(code int) *TemplatesGetByNameDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the templates get by name default response
func (o *TemplatesGetByNameDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the templates get by name default response
func (o *TemplatesGetByNameDefault) WithPayload(payload *models.Error) *TemplatesGetByNameDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the templates get by name default response
func (o *TemplatesGetByNameDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *TemplatesGetByNameDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
