package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	context "golang.org/x/net/context"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ViewsGetByIDHandlerFunc turns a function with the right signature into a views get by Id handler
type ViewsGetByIDHandlerFunc func(context.Context, ViewsGetByIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ViewsGetByIDHandlerFunc) Handle(ctx context.Context, params ViewsGetByIDParams) middleware.Responder {
	return fn(ctx, params)
}

// ViewsGetByIDHandler interface for that can handle valid views get by Id params
type ViewsGetByIDHandler interface {
	Handle(context.Context, ViewsGetByIDParams) middleware.Responder
}

// NewViewsGetByID creates a new http.Handler for the views get by Id operation
func NewViewsGetByID(ctx *middleware.Context, handler ViewsGetByIDHandler) *ViewsGetByID {
	return &ViewsGetByID{Context: ctx, Handler: handler}
}

/*ViewsGetByID swagger:route GET /views/{identifier} /api/2.0 viewsGetById

Get the specified view

Get the view with the specified file name.

*/
type ViewsGetByID struct {
	Context *middleware.Context
	Handler ViewsGetByIDHandler
}

func (o *ViewsGetByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewViewsGetByIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(context.Background(), Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// ViewsGetByIDOKBody views get by ID o k body
// swagger:model ViewsGetByIDOKBody
type ViewsGetByIDOKBody interface{}
