package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/RackHD/neighborhood-manager/rackhd/api/swagger/models"
)

/*WorkflowsGetAllTasksOK Successfully retrieved workflow tasks

swagger:response workflowsGetAllTasksOK
*/
type WorkflowsGetAllTasksOK struct {

	// In: body
	Payload WorkflowsGetAllTasksOKBody `json:"body,omitempty"`
}

// NewWorkflowsGetAllTasksOK creates WorkflowsGetAllTasksOK with default headers values
func NewWorkflowsGetAllTasksOK() *WorkflowsGetAllTasksOK {
	return &WorkflowsGetAllTasksOK{}
}

// WithPayload adds the payload to the workflows get all tasks o k response
func (o *WorkflowsGetAllTasksOK) WithPayload(payload WorkflowsGetAllTasksOKBody) *WorkflowsGetAllTasksOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the workflows get all tasks o k response
func (o *WorkflowsGetAllTasksOK) SetPayload(payload WorkflowsGetAllTasksOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *WorkflowsGetAllTasksOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*WorkflowsGetAllTasksDefault Unexpected error

swagger:response workflowsGetAllTasksDefault
*/
type WorkflowsGetAllTasksDefault struct {
	_statusCode int

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewWorkflowsGetAllTasksDefault creates WorkflowsGetAllTasksDefault with default headers values
func NewWorkflowsGetAllTasksDefault(code int) *WorkflowsGetAllTasksDefault {
	if code <= 0 {
		code = 500
	}

	return &WorkflowsGetAllTasksDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the workflows get all tasks default response
func (o *WorkflowsGetAllTasksDefault) WithStatusCode(code int) *WorkflowsGetAllTasksDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the workflows get all tasks default response
func (o *WorkflowsGetAllTasksDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the workflows get all tasks default response
func (o *WorkflowsGetAllTasksDefault) WithPayload(payload *models.Error) *WorkflowsGetAllTasksDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the workflows get all tasks default response
func (o *WorkflowsGetAllTasksDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *WorkflowsGetAllTasksDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
