package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/RackHD/neighborhood-manager/swagger/models"
)

/*CreateTagCreated Successfully created the tag

swagger:response createTagCreated
*/
type CreateTagCreated struct {

	// In: body
	Payload CreateTagCreatedBody `json:"body,omitempty"`
}

// NewCreateTagCreated creates CreateTagCreated with default headers values
func NewCreateTagCreated() *CreateTagCreated {
	return &CreateTagCreated{}
}

// WithPayload adds the payload to the create tag created response
func (o *CreateTagCreated) WithPayload(payload CreateTagCreatedBody) *CreateTagCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create tag created response
func (o *CreateTagCreated) SetPayload(payload CreateTagCreatedBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateTagCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*CreateTagInternalServerError The tag could not be created

swagger:response createTagInternalServerError
*/
type CreateTagInternalServerError struct {

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateTagInternalServerError creates CreateTagInternalServerError with default headers values
func NewCreateTagInternalServerError() *CreateTagInternalServerError {
	return &CreateTagInternalServerError{}
}

// WithPayload adds the payload to the create tag internal server error response
func (o *CreateTagInternalServerError) WithPayload(payload *models.Error) *CreateTagInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create tag internal server error response
func (o *CreateTagInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateTagInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*CreateTagDefault Unexpected error

swagger:response createTagDefault
*/
type CreateTagDefault struct {
	_statusCode int

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateTagDefault creates CreateTagDefault with default headers values
func NewCreateTagDefault(code int) *CreateTagDefault {
	if code <= 0 {
		code = 500
	}

	return &CreateTagDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the create tag default response
func (o *CreateTagDefault) WithStatusCode(code int) *CreateTagDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the create tag default response
func (o *CreateTagDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the create tag default response
func (o *CreateTagDefault) WithPayload(payload *models.Error) *CreateTagDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create tag default response
func (o *CreateTagDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateTagDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
