package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/RackHD/neighborhood-manager/swagger/models"
)

/*FilesMd5GetOK Successfully retrieved the md5sum of the specified file

swagger:response filesMd5GetOK
*/
type FilesMd5GetOK struct {

	// In: body
	Payload FilesMd5GetOKBody `json:"body,omitempty"`
}

// NewFilesMd5GetOK creates FilesMd5GetOK with default headers values
func NewFilesMd5GetOK() *FilesMd5GetOK {
	return &FilesMd5GetOK{}
}

// WithPayload adds the payload to the files md5 get o k response
func (o *FilesMd5GetOK) WithPayload(payload FilesMd5GetOKBody) *FilesMd5GetOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the files md5 get o k response
func (o *FilesMd5GetOK) SetPayload(payload FilesMd5GetOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FilesMd5GetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*FilesMd5GetNotFound File not found

swagger:response filesMd5GetNotFound
*/
type FilesMd5GetNotFound struct {

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewFilesMd5GetNotFound creates FilesMd5GetNotFound with default headers values
func NewFilesMd5GetNotFound() *FilesMd5GetNotFound {
	return &FilesMd5GetNotFound{}
}

// WithPayload adds the payload to the files md5 get not found response
func (o *FilesMd5GetNotFound) WithPayload(payload *models.Error) *FilesMd5GetNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the files md5 get not found response
func (o *FilesMd5GetNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FilesMd5GetNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*FilesMd5GetInternalServerError Failed to serve file request

swagger:response filesMd5GetInternalServerError
*/
type FilesMd5GetInternalServerError struct {

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewFilesMd5GetInternalServerError creates FilesMd5GetInternalServerError with default headers values
func NewFilesMd5GetInternalServerError() *FilesMd5GetInternalServerError {
	return &FilesMd5GetInternalServerError{}
}

// WithPayload adds the payload to the files md5 get internal server error response
func (o *FilesMd5GetInternalServerError) WithPayload(payload *models.Error) *FilesMd5GetInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the files md5 get internal server error response
func (o *FilesMd5GetInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FilesMd5GetInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*FilesMd5GetDefault Unexpected error

swagger:response filesMd5GetDefault
*/
type FilesMd5GetDefault struct {
	_statusCode int

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewFilesMd5GetDefault creates FilesMd5GetDefault with default headers values
func NewFilesMd5GetDefault(code int) *FilesMd5GetDefault {
	if code <= 0 {
		code = 500
	}

	return &FilesMd5GetDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the files md5 get default response
func (o *FilesMd5GetDefault) WithStatusCode(code int) *FilesMd5GetDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the files md5 get default response
func (o *FilesMd5GetDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the files md5 get default response
func (o *FilesMd5GetDefault) WithPayload(payload *models.Error) *FilesMd5GetDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the files md5 get default response
func (o *FilesMd5GetDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FilesMd5GetDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
