package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewNodesGetCatalogSourceByIDParams creates a new NodesGetCatalogSourceByIDParams object
// with the default values initialized.
func NewNodesGetCatalogSourceByIDParams() NodesGetCatalogSourceByIDParams {
	var ()
	return NodesGetCatalogSourceByIDParams{}
}

// NodesGetCatalogSourceByIDParams contains all the bound params for the nodes get catalog source by Id operation
// typically these are obtained from a http.Request
//
// swagger:parameters nodesGetCatalogSourceById
type NodesGetCatalogSourceByIDParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*The node identifier
	  Required: true
	  In: path
	*/
	Identifier string
	/*The source catalog name to fetch
	  Required: true
	  In: path
	*/
	Source string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *NodesGetCatalogSourceByIDParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	rIdentifier, rhkIdentifier, _ := route.Params.GetOK("identifier")
	if err := o.bindIdentifier(rIdentifier, rhkIdentifier, route.Formats); err != nil {
		res = append(res, err)
	}

	rSource, rhkSource, _ := route.Params.GetOK("source")
	if err := o.bindSource(rSource, rhkSource, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *NodesGetCatalogSourceByIDParams) bindIdentifier(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.Identifier = raw

	return nil
}

func (o *NodesGetCatalogSourceByIDParams) bindSource(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.Source = raw

	return nil
}
