package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/RackHD/neighborhood-manager/swagger/models"
)

/*NodesAddRelationsOK update succeeded

swagger:response nodesAddRelationsOK
*/
type NodesAddRelationsOK struct {

	// In: body
	Payload NodesAddRelationsOKBody `json:"body,omitempty"`
}

// NewNodesAddRelationsOK creates NodesAddRelationsOK with default headers values
func NewNodesAddRelationsOK() *NodesAddRelationsOK {
	return &NodesAddRelationsOK{}
}

// WithPayload adds the payload to the nodes add relations o k response
func (o *NodesAddRelationsOK) WithPayload(payload NodesAddRelationsOKBody) *NodesAddRelationsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the nodes add relations o k response
func (o *NodesAddRelationsOK) SetPayload(payload NodesAddRelationsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NodesAddRelationsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*NodesAddRelationsNotFound Not found

swagger:response nodesAddRelationsNotFound
*/
type NodesAddRelationsNotFound struct {

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewNodesAddRelationsNotFound creates NodesAddRelationsNotFound with default headers values
func NewNodesAddRelationsNotFound() *NodesAddRelationsNotFound {
	return &NodesAddRelationsNotFound{}
}

// WithPayload adds the payload to the nodes add relations not found response
func (o *NodesAddRelationsNotFound) WithPayload(payload *models.Error) *NodesAddRelationsNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the nodes add relations not found response
func (o *NodesAddRelationsNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NodesAddRelationsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NodesAddRelationsDefault Unexpected error

swagger:response nodesAddRelationsDefault
*/
type NodesAddRelationsDefault struct {
	_statusCode int

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewNodesAddRelationsDefault creates NodesAddRelationsDefault with default headers values
func NewNodesAddRelationsDefault(code int) *NodesAddRelationsDefault {
	if code <= 0 {
		code = 500
	}

	return &NodesAddRelationsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the nodes add relations default response
func (o *NodesAddRelationsDefault) WithStatusCode(code int) *NodesAddRelationsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the nodes add relations default response
func (o *NodesAddRelationsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the nodes add relations default response
func (o *NodesAddRelationsDefault) WithPayload(payload *models.Error) *NodesAddRelationsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the nodes add relations default response
func (o *NodesAddRelationsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NodesAddRelationsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
