package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// NodesGetCatalogSourceByIDHandlerFunc turns a function with the right signature into a nodes get catalog source by Id handler
type NodesGetCatalogSourceByIDHandlerFunc func(NodesGetCatalogSourceByIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NodesGetCatalogSourceByIDHandlerFunc) Handle(params NodesGetCatalogSourceByIDParams) middleware.Responder {
	return fn(params)
}

// NodesGetCatalogSourceByIDHandler interface for that can handle valid nodes get catalog source by Id params
type NodesGetCatalogSourceByIDHandler interface {
	Handle(NodesGetCatalogSourceByIDParams) middleware.Responder
}

// NewNodesGetCatalogSourceByID creates a new http.Handler for the nodes get catalog source by Id operation
func NewNodesGetCatalogSourceByID(ctx *middleware.Context, handler NodesGetCatalogSourceByIDHandler) *NodesGetCatalogSourceByID {
	return &NodesGetCatalogSourceByID{Context: ctx, Handler: handler}
}

/*NodesGetCatalogSourceByID swagger:route GET /nodes/{identifier}/catalogs/{source} /api/2.0 nodesGetCatalogSourceById

Get the catalogs for a node

Get a list of all of the catalogs for the specified node, containing the specified value of the source catalog property.

*/
type NodesGetCatalogSourceByID struct {
	Context *middleware.Context
	Handler NodesGetCatalogSourceByIDHandler
}

func (o *NodesGetCatalogSourceByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewNodesGetCatalogSourceByIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// NodesGetCatalogSourceByIDOKBody nodes get catalog source by ID o k body
// swagger:model NodesGetCatalogSourceByIDOKBody
type NodesGetCatalogSourceByIDOKBody interface{}
