package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/RackHD/neighborhood-manager/swagger/models"
)

/*NodesDelTagByIDNoContent Successfully deleted tag

swagger:response nodesDelTagByIdNoContent
*/
type NodesDelTagByIDNoContent struct {
}

// NewNodesDelTagByIDNoContent creates NodesDelTagByIDNoContent with default headers values
func NewNodesDelTagByIDNoContent() *NodesDelTagByIDNoContent {
	return &NodesDelTagByIDNoContent{}
}

// WriteResponse to the client
func (o *NodesDelTagByIDNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(204)
}

/*NodesDelTagByIDNotFound The specified node was not found

swagger:response nodesDelTagByIdNotFound
*/
type NodesDelTagByIDNotFound struct {

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewNodesDelTagByIDNotFound creates NodesDelTagByIDNotFound with default headers values
func NewNodesDelTagByIDNotFound() *NodesDelTagByIDNotFound {
	return &NodesDelTagByIDNotFound{}
}

// WithPayload adds the payload to the nodes del tag by Id not found response
func (o *NodesDelTagByIDNotFound) WithPayload(payload *models.Error) *NodesDelTagByIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the nodes del tag by Id not found response
func (o *NodesDelTagByIDNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NodesDelTagByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NodesDelTagByIDDefault Unexpected error

swagger:response nodesDelTagByIdDefault
*/
type NodesDelTagByIDDefault struct {
	_statusCode int

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewNodesDelTagByIDDefault creates NodesDelTagByIDDefault with default headers values
func NewNodesDelTagByIDDefault(code int) *NodesDelTagByIDDefault {
	if code <= 0 {
		code = 500
	}

	return &NodesDelTagByIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the nodes del tag by Id default response
func (o *NodesDelTagByIDDefault) WithStatusCode(code int) *NodesDelTagByIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the nodes del tag by Id default response
func (o *NodesDelTagByIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the nodes del tag by Id default response
func (o *NodesDelTagByIDDefault) WithPayload(payload *models.Error) *NodesDelTagByIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the nodes del tag by Id default response
func (o *NodesDelTagByIDDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NodesDelTagByIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
