package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/RackHD/neighborhood-manager/swagger/models"
)

/*NodesGetByIDOK Successfully retrieved the list of nodes

swagger:response nodesGetByIdOK
*/
type NodesGetByIDOK struct {

	// In: body
	Payload []interface{} `json:"body,omitempty"`
}

// NewNodesGetByIDOK creates NodesGetByIDOK with default headers values
func NewNodesGetByIDOK() *NodesGetByIDOK {
	return &NodesGetByIDOK{}
}

// WithPayload adds the payload to the nodes get by Id o k response
func (o *NodesGetByIDOK) WithPayload(payload []interface{}) *NodesGetByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the nodes get by Id o k response
func (o *NodesGetByIDOK) SetPayload(payload []interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NodesGetByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*NodesGetByIDNotFound The specified node was not found

swagger:response nodesGetByIdNotFound
*/
type NodesGetByIDNotFound struct {

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewNodesGetByIDNotFound creates NodesGetByIDNotFound with default headers values
func NewNodesGetByIDNotFound() *NodesGetByIDNotFound {
	return &NodesGetByIDNotFound{}
}

// WithPayload adds the payload to the nodes get by Id not found response
func (o *NodesGetByIDNotFound) WithPayload(payload *models.Error) *NodesGetByIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the nodes get by Id not found response
func (o *NodesGetByIDNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NodesGetByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NodesGetByIDDefault Unexpected error

swagger:response nodesGetByIdDefault
*/
type NodesGetByIDDefault struct {
	_statusCode int

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewNodesGetByIDDefault creates NodesGetByIDDefault with default headers values
func NewNodesGetByIDDefault(code int) *NodesGetByIDDefault {
	if code <= 0 {
		code = 500
	}

	return &NodesGetByIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the nodes get by Id default response
func (o *NodesGetByIDDefault) WithStatusCode(code int) *NodesGetByIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the nodes get by Id default response
func (o *NodesGetByIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the nodes get by Id default response
func (o *NodesGetByIDDefault) WithPayload(payload *models.Error) *NodesGetByIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the nodes get by Id default response
func (o *NodesGetByIDDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NodesGetByIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
