package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/RackHD/neighborhood-manager/swagger/models"
)

/*NodesGetPollersByIDOK Successfully retrieved the pollers of specified node

swagger:response nodesGetPollersByIdOK
*/
type NodesGetPollersByIDOK struct {

	// In: body
	Payload NodesGetPollersByIDOKBody `json:"body,omitempty"`
}

// NewNodesGetPollersByIDOK creates NodesGetPollersByIDOK with default headers values
func NewNodesGetPollersByIDOK() *NodesGetPollersByIDOK {
	return &NodesGetPollersByIDOK{}
}

// WithPayload adds the payload to the nodes get pollers by Id o k response
func (o *NodesGetPollersByIDOK) WithPayload(payload NodesGetPollersByIDOKBody) *NodesGetPollersByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the nodes get pollers by Id o k response
func (o *NodesGetPollersByIDOK) SetPayload(payload NodesGetPollersByIDOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NodesGetPollersByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*NodesGetPollersByIDNotFound The specified node was not found

swagger:response nodesGetPollersByIdNotFound
*/
type NodesGetPollersByIDNotFound struct {

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewNodesGetPollersByIDNotFound creates NodesGetPollersByIDNotFound with default headers values
func NewNodesGetPollersByIDNotFound() *NodesGetPollersByIDNotFound {
	return &NodesGetPollersByIDNotFound{}
}

// WithPayload adds the payload to the nodes get pollers by Id not found response
func (o *NodesGetPollersByIDNotFound) WithPayload(payload *models.Error) *NodesGetPollersByIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the nodes get pollers by Id not found response
func (o *NodesGetPollersByIDNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NodesGetPollersByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NodesGetPollersByIDDefault Unexpected error

swagger:response nodesGetPollersByIdDefault
*/
type NodesGetPollersByIDDefault struct {
	_statusCode int

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewNodesGetPollersByIDDefault creates NodesGetPollersByIDDefault with default headers values
func NewNodesGetPollersByIDDefault(code int) *NodesGetPollersByIDDefault {
	if code <= 0 {
		code = 500
	}

	return &NodesGetPollersByIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the nodes get pollers by Id default response
func (o *NodesGetPollersByIDDefault) WithStatusCode(code int) *NodesGetPollersByIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the nodes get pollers by Id default response
func (o *NodesGetPollersByIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the nodes get pollers by Id default response
func (o *NodesGetPollersByIDDefault) WithPayload(payload *models.Error) *NodesGetPollersByIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the nodes get pollers by Id default response
func (o *NodesGetPollersByIDDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NodesGetPollersByIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
