package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewNodesDelTagByIDParams creates a new NodesDelTagByIDParams object
// with the default values initialized.
func NewNodesDelTagByIDParams() NodesDelTagByIDParams {
	var ()
	return NodesDelTagByIDParams{}
}

// NodesDelTagByIDParams contains all the bound params for the nodes del tag by Id operation
// typically these are obtained from a http.Request
//
// swagger:parameters nodesDelTagById
type NodesDelTagByIDParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*The node identifier
	  Required: true
	  In: path
	*/
	Identifier string
	/*The name of the tag
	  Required: true
	  In: path
	*/
	TagName string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *NodesDelTagByIDParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	rIdentifier, rhkIdentifier, _ := route.Params.GetOK("identifier")
	if err := o.bindIdentifier(rIdentifier, rhkIdentifier, route.Formats); err != nil {
		res = append(res, err)
	}

	rTagName, rhkTagName, _ := route.Params.GetOK("tagName")
	if err := o.bindTagName(rTagName, rhkTagName, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *NodesDelTagByIDParams) bindIdentifier(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.Identifier = raw

	return nil
}

func (o *NodesDelTagByIDParams) bindTagName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.TagName = raw

	return nil
}
