package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/RackHD/neighborhood-manager/swagger/models"
)

/*ObmsPostLedCreated OBM settings accepted

swagger:response obmsPostLedCreated
*/
type ObmsPostLedCreated struct {
}

// NewObmsPostLedCreated creates ObmsPostLedCreated with default headers values
func NewObmsPostLedCreated() *ObmsPostLedCreated {
	return &ObmsPostLedCreated{}
}

// WriteResponse to the client
func (o *ObmsPostLedCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
}

/*ObmsPostLedNotFound The node with the identifier was not found or has no obm settings

swagger:response obmsPostLedNotFound
*/
type ObmsPostLedNotFound struct {

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewObmsPostLedNotFound creates ObmsPostLedNotFound with default headers values
func NewObmsPostLedNotFound() *ObmsPostLedNotFound {
	return &ObmsPostLedNotFound{}
}

// WithPayload adds the payload to the obms post led not found response
func (o *ObmsPostLedNotFound) WithPayload(payload *models.Error) *ObmsPostLedNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the obms post led not found response
func (o *ObmsPostLedNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ObmsPostLedNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*ObmsPostLedDefault Unexpected error

swagger:response obmsPostLedDefault
*/
type ObmsPostLedDefault struct {
	_statusCode int

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewObmsPostLedDefault creates ObmsPostLedDefault with default headers values
func NewObmsPostLedDefault(code int) *ObmsPostLedDefault {
	if code <= 0 {
		code = 500
	}

	return &ObmsPostLedDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the obms post led default response
func (o *ObmsPostLedDefault) WithStatusCode(code int) *ObmsPostLedDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the obms post led default response
func (o *ObmsPostLedDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the obms post led default response
func (o *ObmsPostLedDefault) WithPayload(payload *models.Error) *ObmsPostLedDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the obms post led default response
func (o *ObmsPostLedDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ObmsPostLedDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
