package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ProfilesGetMetadataByNameHandlerFunc turns a function with the right signature into a profiles get metadata by name handler
type ProfilesGetMetadataByNameHandlerFunc func(ProfilesGetMetadataByNameParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ProfilesGetMetadataByNameHandlerFunc) Handle(params ProfilesGetMetadataByNameParams) middleware.Responder {
	return fn(params)
}

// ProfilesGetMetadataByNameHandler interface for that can handle valid profiles get metadata by name params
type ProfilesGetMetadataByNameHandler interface {
	Handle(ProfilesGetMetadataByNameParams) middleware.Responder
}

// NewProfilesGetMetadataByName creates a new http.Handler for the profiles get metadata by name operation
func NewProfilesGetMetadataByName(ctx *middleware.Context, handler ProfilesGetMetadataByNameHandler) *ProfilesGetMetadataByName {
	return &ProfilesGetMetadataByName{Context: ctx, Handler: handler}
}

/*ProfilesGetMetadataByName swagger:route GET /profiles/metadata/{name} /api/2.0 profilesGetMetadataByName

Get a single profiles metadata from database

Get the metadata associated with the specified profile.

*/
type ProfilesGetMetadataByName struct {
	Context *middleware.Context
	Handler ProfilesGetMetadataByNameHandler
}

func (o *ProfilesGetMetadataByName) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewProfilesGetMetadataByNameParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// ProfilesGetMetadataByNameOKBody profiles get metadata by name o k body
// swagger:model ProfilesGetMetadataByNameOKBody
type ProfilesGetMetadataByNameOKBody interface{}
