package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewProfilesGetSwitchVendorParams creates a new ProfilesGetSwitchVendorParams object
// with the default values initialized.
func NewProfilesGetSwitchVendorParams() ProfilesGetSwitchVendorParams {
	var ()
	return ProfilesGetSwitchVendorParams{}
}

// ProfilesGetSwitchVendorParams contains all the bound params for the profiles get switch vendor operation
// typically these are obtained from a http.Request
//
// swagger:parameters profilesGetSwitchVendor
type ProfilesGetSwitchVendorParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*The switch vendor name
	  Required: true
	  In: path
	*/
	Vendor string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *ProfilesGetSwitchVendorParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	rVendor, rhkVendor, _ := route.Params.GetOK("vendor")
	if err := o.bindVendor(rVendor, rhkVendor, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ProfilesGetSwitchVendorParams) bindVendor(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.Vendor = raw

	return nil
}
