package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/RackHD/neighborhood-manager/swagger/models"
)

/*SkusPostCreated Successfully created the SKU

swagger:response skusPostCreated
*/
type SkusPostCreated struct {

	// In: body
	Payload SkusPostCreatedBody `json:"body,omitempty"`
}

// NewSkusPostCreated creates SkusPostCreated with default headers values
func NewSkusPostCreated() *SkusPostCreated {
	return &SkusPostCreated{}
}

// WithPayload adds the payload to the skus post created response
func (o *SkusPostCreated) WithPayload(payload SkusPostCreatedBody) *SkusPostCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the skus post created response
func (o *SkusPostCreated) SetPayload(payload SkusPostCreatedBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SkusPostCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*SkusPostInternalServerError Upload failed.

swagger:response skusPostInternalServerError
*/
type SkusPostInternalServerError struct {

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewSkusPostInternalServerError creates SkusPostInternalServerError with default headers values
func NewSkusPostInternalServerError() *SkusPostInternalServerError {
	return &SkusPostInternalServerError{}
}

// WithPayload adds the payload to the skus post internal server error response
func (o *SkusPostInternalServerError) WithPayload(payload *models.Error) *SkusPostInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the skus post internal server error response
func (o *SkusPostInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SkusPostInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*SkusPostDefault Unexpected error

swagger:response skusPostDefault
*/
type SkusPostDefault struct {
	_statusCode int

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewSkusPostDefault creates SkusPostDefault with default headers values
func NewSkusPostDefault(code int) *SkusPostDefault {
	if code <= 0 {
		code = 500
	}

	return &SkusPostDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the skus post default response
func (o *SkusPostDefault) WithStatusCode(code int) *SkusPostDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the skus post default response
func (o *SkusPostDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the skus post default response
func (o *SkusPostDefault) WithPayload(payload *models.Error) *SkusPostDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the skus post default response
func (o *SkusPostDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SkusPostDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
