package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/RackHD/neighborhood-manager/swagger/models"
)

/*SkusPutCreated Successfully created or updated SKU definition

swagger:response skusPutCreated
*/
type SkusPutCreated struct {

	// In: body
	Payload SkusPutCreatedBody `json:"body,omitempty"`
}

// NewSkusPutCreated creates SkusPutCreated with default headers values
func NewSkusPutCreated() *SkusPutCreated {
	return &SkusPutCreated{}
}

// WithPayload adds the payload to the skus put created response
func (o *SkusPutCreated) WithPayload(payload SkusPutCreatedBody) *SkusPutCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the skus put created response
func (o *SkusPutCreated) SetPayload(payload SkusPutCreatedBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SkusPutCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*SkusPutInternalServerError Update failed

swagger:response skusPutInternalServerError
*/
type SkusPutInternalServerError struct {

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewSkusPutInternalServerError creates SkusPutInternalServerError with default headers values
func NewSkusPutInternalServerError() *SkusPutInternalServerError {
	return &SkusPutInternalServerError{}
}

// WithPayload adds the payload to the skus put internal server error response
func (o *SkusPutInternalServerError) WithPayload(payload *models.Error) *SkusPutInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the skus put internal server error response
func (o *SkusPutInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SkusPutInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*SkusPutDefault Unexpected error

swagger:response skusPutDefault
*/
type SkusPutDefault struct {
	_statusCode int

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewSkusPutDefault creates SkusPutDefault with default headers values
func NewSkusPutDefault(code int) *SkusPutDefault {
	if code <= 0 {
		code = 500
	}

	return &SkusPutDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the skus put default response
func (o *SkusPutDefault) WithStatusCode(code int) *SkusPutDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the skus put default response
func (o *SkusPutDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the skus put default response
func (o *SkusPutDefault) WithPayload(payload *models.Error) *SkusPutDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the skus put default response
func (o *SkusPutDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SkusPutDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
