package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/RackHD/neighborhood-manager/swagger/models"
)

/*SkusIDDeleteNoContent Successfully deleted the SKU

swagger:response skusIdDeleteNoContent
*/
type SkusIDDeleteNoContent struct {

	// In: body
	Payload SkusIDDeleteNoContentBody `json:"body,omitempty"`
}

// NewSkusIDDeleteNoContent creates SkusIDDeleteNoContent with default headers values
func NewSkusIDDeleteNoContent() *SkusIDDeleteNoContent {
	return &SkusIDDeleteNoContent{}
}

// WithPayload adds the payload to the skus Id delete no content response
func (o *SkusIDDeleteNoContent) WithPayload(payload SkusIDDeleteNoContentBody) *SkusIDDeleteNoContent {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the skus Id delete no content response
func (o *SkusIDDeleteNoContent) SetPayload(payload SkusIDDeleteNoContentBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SkusIDDeleteNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(204)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*SkusIDDeleteNotFound The SKU with the specified identifier was not found

swagger:response skusIdDeleteNotFound
*/
type SkusIDDeleteNotFound struct {

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewSkusIDDeleteNotFound creates SkusIDDeleteNotFound with default headers values
func NewSkusIDDeleteNotFound() *SkusIDDeleteNotFound {
	return &SkusIDDeleteNotFound{}
}

// WithPayload adds the payload to the skus Id delete not found response
func (o *SkusIDDeleteNotFound) WithPayload(payload *models.Error) *SkusIDDeleteNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the skus Id delete not found response
func (o *SkusIDDeleteNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SkusIDDeleteNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*SkusIDDeleteDefault Unexpected error

swagger:response skusIdDeleteDefault
*/
type SkusIDDeleteDefault struct {
	_statusCode int

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewSkusIDDeleteDefault creates SkusIDDeleteDefault with default headers values
func NewSkusIDDeleteDefault(code int) *SkusIDDeleteDefault {
	if code <= 0 {
		code = 500
	}

	return &SkusIDDeleteDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the skus Id delete default response
func (o *SkusIDDeleteDefault) WithStatusCode(code int) *SkusIDDeleteDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the skus Id delete default response
func (o *SkusIDDeleteDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the skus Id delete default response
func (o *SkusIDDeleteDefault) WithPayload(payload *models.Error) *SkusIDDeleteDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the skus Id delete default response
func (o *SkusIDDeleteDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SkusIDDeleteDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
