package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewTaskSchemasIDGetParams creates a new TaskSchemasIDGetParams object
// with the default values initialized.
func NewTaskSchemasIDGetParams() TaskSchemasIDGetParams {
	var ()
	return TaskSchemasIDGetParams{}
}

// TaskSchemasIDGetParams contains all the bound params for the task schemas Id get operation
// typically these are obtained from a http.Request
//
// swagger:parameters taskSchemasIdGet
type TaskSchemasIDGetParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*The filename of the task schema
	  Required: true
	  In: path
	*/
	Identifier string
	/*The reference resolve flag. false - a simple schema with any internal reference only in the response. true - all the internal references will be resolved and fully defined in the response.

	  In: query
	*/
	ResolveRef *bool
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *TaskSchemasIDGetParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	rIdentifier, rhkIdentifier, _ := route.Params.GetOK("identifier")
	if err := o.bindIdentifier(rIdentifier, rhkIdentifier, route.Formats); err != nil {
		res = append(res, err)
	}

	qResolveRef, qhkResolveRef, _ := qs.GetOK("resolveRef")
	if err := o.bindResolveRef(qResolveRef, qhkResolveRef, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *TaskSchemasIDGetParams) bindIdentifier(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.Identifier = raw

	return nil
}

func (o *TaskSchemasIDGetParams) bindResolveRef(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertBool(raw)
	if err != nil {
		return errors.InvalidType("resolveRef", "query", "bool", raw)
	}
	o.ResolveRef = &value

	return nil
}
