package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewWorkflowsGetTasksByNameParams creates a new WorkflowsGetTasksByNameParams object
// with the default values initialized.
func NewWorkflowsGetTasksByNameParams() WorkflowsGetTasksByNameParams {
	var ()
	return WorkflowsGetTasksByNameParams{}
}

// WorkflowsGetTasksByNameParams contains all the bound params for the workflows get tasks by name operation
// typically these are obtained from a http.Request
//
// swagger:parameters workflowsGetTasksByName
type WorkflowsGetTasksByNameParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*The task injectable name
	  Required: true
	  In: path
	*/
	InjectableName string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *WorkflowsGetTasksByNameParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	rInjectableName, rhkInjectableName, _ := route.Params.GetOK("injectableName")
	if err := o.bindInjectableName(rInjectableName, rhkInjectableName, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *WorkflowsGetTasksByNameParams) bindInjectableName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.InjectableName = raw

	return nil
}
