package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewFilesPutParams creates a new FilesPutParams object
// with the default values initialized.
func NewFilesPutParams() FilesPutParams {
	var ()
	return FilesPutParams{}
}

// FilesPutParams contains all the bound params for the files put operation
// typically these are obtained from a http.Request
//
// swagger:parameters filesPut
type FilesPutParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*The filename of the file you want to store
	  Required: true
	  In: path
	*/
	Fileidentifier string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *FilesPutParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	rFileidentifier, rhkFileidentifier, _ := route.Params.GetOK("fileidentifier")
	if err := o.bindFileidentifier(rFileidentifier, rhkFileidentifier, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *FilesPutParams) bindFileidentifier(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.Fileidentifier = raw

	return nil
}
