package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/RackHD/neighborhood-manager/swagger/models"
)

/*NodesDelRelationsNoContent Successfully removed the relations

swagger:response nodesDelRelationsNoContent
*/
type NodesDelRelationsNoContent struct {
}

// NewNodesDelRelationsNoContent creates NodesDelRelationsNoContent with default headers values
func NewNodesDelRelationsNoContent() *NodesDelRelationsNoContent {
	return &NodesDelRelationsNoContent{}
}

// WriteResponse to the client
func (o *NodesDelRelationsNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(204)
}

/*NodesDelRelationsNotFound The node with the identifier was not found.

swagger:response nodesDelRelationsNotFound
*/
type NodesDelRelationsNotFound struct {

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewNodesDelRelationsNotFound creates NodesDelRelationsNotFound with default headers values
func NewNodesDelRelationsNotFound() *NodesDelRelationsNotFound {
	return &NodesDelRelationsNotFound{}
}

// WithPayload adds the payload to the nodes del relations not found response
func (o *NodesDelRelationsNotFound) WithPayload(payload *models.Error) *NodesDelRelationsNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the nodes del relations not found response
func (o *NodesDelRelationsNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NodesDelRelationsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NodesDelRelationsDefault Unexpected error

swagger:response nodesDelRelationsDefault
*/
type NodesDelRelationsDefault struct {
	_statusCode int

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewNodesDelRelationsDefault creates NodesDelRelationsDefault with default headers values
func NewNodesDelRelationsDefault(code int) *NodesDelRelationsDefault {
	if code <= 0 {
		code = 500
	}

	return &NodesDelRelationsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the nodes del relations default response
func (o *NodesDelRelationsDefault) WithStatusCode(code int) *NodesDelRelationsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the nodes del relations default response
func (o *NodesDelRelationsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the nodes del relations default response
func (o *NodesDelRelationsDefault) WithPayload(payload *models.Error) *NodesDelRelationsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the nodes del relations default response
func (o *NodesDelRelationsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NodesDelRelationsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
