package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/RackHD/neighborhood-manager/swagger/models"
)

/*NodesGetRelationsOK Successfully retrieved the nodes relations

swagger:response nodesGetRelationsOK
*/
type NodesGetRelationsOK struct {

	// In: body
	Payload []interface{} `json:"body,omitempty"`
}

// NewNodesGetRelationsOK creates NodesGetRelationsOK with default headers values
func NewNodesGetRelationsOK() *NodesGetRelationsOK {
	return &NodesGetRelationsOK{}
}

// WithPayload adds the payload to the nodes get relations o k response
func (o *NodesGetRelationsOK) WithPayload(payload []interface{}) *NodesGetRelationsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the nodes get relations o k response
func (o *NodesGetRelationsOK) SetPayload(payload []interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NodesGetRelationsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*NodesGetRelationsNotFound The node with the identifier was not found.

swagger:response nodesGetRelationsNotFound
*/
type NodesGetRelationsNotFound struct {

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewNodesGetRelationsNotFound creates NodesGetRelationsNotFound with default headers values
func NewNodesGetRelationsNotFound() *NodesGetRelationsNotFound {
	return &NodesGetRelationsNotFound{}
}

// WithPayload adds the payload to the nodes get relations not found response
func (o *NodesGetRelationsNotFound) WithPayload(payload *models.Error) *NodesGetRelationsNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the nodes get relations not found response
func (o *NodesGetRelationsNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NodesGetRelationsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NodesGetRelationsDefault Unexpected error

swagger:response nodesGetRelationsDefault
*/
type NodesGetRelationsDefault struct {
	_statusCode int

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewNodesGetRelationsDefault creates NodesGetRelationsDefault with default headers values
func NewNodesGetRelationsDefault(code int) *NodesGetRelationsDefault {
	if code <= 0 {
		code = 500
	}

	return &NodesGetRelationsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the nodes get relations default response
func (o *NodesGetRelationsDefault) WithStatusCode(code int) *NodesGetRelationsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the nodes get relations default response
func (o *NodesGetRelationsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the nodes get relations default response
func (o *NodesGetRelationsDefault) WithPayload(payload *models.Error) *NodesGetRelationsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the nodes get relations default response
func (o *NodesGetRelationsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NodesGetRelationsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
