package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/RackHD/neighborhood-manager/swagger/models"
)

// NewObmsPutParams creates a new ObmsPutParams object
// with the default values initialized.
func NewObmsPutParams() ObmsPutParams {
	var ()
	return ObmsPutParams{}
}

// ObmsPutParams contains all the bound params for the obms put operation
// typically these are obtained from a http.Request
//
// swagger:parameters obmsPut
type ObmsPutParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*The OBM settings information to create
	  Required: true
	  In: body
	*/
	Body *models.IPMIObmServiceObm
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *ObmsPutParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.IPMIObmServiceObm
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("body", "body"))
			} else {
				res = append(res, errors.NewParseError("body", "body", "", err))
			}

		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Body = &body
			}
		}

	} else {
		res = append(res, errors.Required("body", "body"))
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
