package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PollersDeleteHandlerFunc turns a function with the right signature into a pollers delete handler
type PollersDeleteHandlerFunc func(PollersDeleteParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PollersDeleteHandlerFunc) Handle(params PollersDeleteParams) middleware.Responder {
	return fn(params)
}

// PollersDeleteHandler interface for that can handle valid pollers delete params
type PollersDeleteHandler interface {
	Handle(PollersDeleteParams) middleware.Responder
}

// NewPollersDelete creates a new http.Handler for the pollers delete operation
func NewPollersDelete(ctx *middleware.Context, handler PollersDeleteHandler) *PollersDelete {
	return &PollersDelete{Context: ctx, Handler: handler}
}

/*PollersDelete swagger:route DELETE /pollers/{identifier} /api/2.0 pollersDelete

Delete the specified poller

Delete the poller with the specified identifier.

*/
type PollersDelete struct {
	Context *middleware.Context
	Handler PollersDeleteHandler
}

func (o *PollersDelete) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewPollersDeleteParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
