package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/RackHD/neighborhood-manager/swagger/models"
)

/*PostTaskByIDCreated Successfully posted the specified task

swagger:response postTaskByIdCreated
*/
type PostTaskByIDCreated struct {

	// In: body
	Payload PostTaskByIDCreatedBody `json:"body,omitempty"`
}

// NewPostTaskByIDCreated creates PostTaskByIDCreated with default headers values
func NewPostTaskByIDCreated() *PostTaskByIDCreated {
	return &PostTaskByIDCreated{}
}

// WithPayload adds the payload to the post task by Id created response
func (o *PostTaskByIDCreated) WithPayload(payload PostTaskByIDCreatedBody) *PostTaskByIDCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post task by Id created response
func (o *PostTaskByIDCreated) SetPayload(payload PostTaskByIDCreatedBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostTaskByIDCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*PostTaskByIDNotFound The specified task was not found

swagger:response postTaskByIdNotFound
*/
type PostTaskByIDNotFound struct {

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostTaskByIDNotFound creates PostTaskByIDNotFound with default headers values
func NewPostTaskByIDNotFound() *PostTaskByIDNotFound {
	return &PostTaskByIDNotFound{}
}

// WithPayload adds the payload to the post task by Id not found response
func (o *PostTaskByIDNotFound) WithPayload(payload *models.Error) *PostTaskByIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post task by Id not found response
func (o *PostTaskByIDNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostTaskByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PostTaskByIDDefault Unexpected error

swagger:response postTaskByIdDefault
*/
type PostTaskByIDDefault struct {
	_statusCode int

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostTaskByIDDefault creates PostTaskByIDDefault with default headers values
func NewPostTaskByIDDefault(code int) *PostTaskByIDDefault {
	if code <= 0 {
		code = 500
	}

	return &PostTaskByIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the post task by Id default response
func (o *PostTaskByIDDefault) WithStatusCode(code int) *PostTaskByIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the post task by Id default response
func (o *PostTaskByIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the post task by Id default response
func (o *PostTaskByIDDefault) WithPayload(payload *models.Error) *PostTaskByIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post task by Id default response
func (o *PostTaskByIDDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostTaskByIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
