package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/RackHD/neighborhood-manager/swagger/models"
)

/*TemplatesMetaGetByNameOK Successfully retrieved the metadata of the template with the specified name

swagger:response templatesMetaGetByNameOK
*/
type TemplatesMetaGetByNameOK struct {

	// In: body
	Payload TemplatesMetaGetByNameOKBody `json:"body,omitempty"`
}

// NewTemplatesMetaGetByNameOK creates TemplatesMetaGetByNameOK with default headers values
func NewTemplatesMetaGetByNameOK() *TemplatesMetaGetByNameOK {
	return &TemplatesMetaGetByNameOK{}
}

// WithPayload adds the payload to the templates meta get by name o k response
func (o *TemplatesMetaGetByNameOK) WithPayload(payload TemplatesMetaGetByNameOKBody) *TemplatesMetaGetByNameOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the templates meta get by name o k response
func (o *TemplatesMetaGetByNameOK) SetPayload(payload TemplatesMetaGetByNameOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *TemplatesMetaGetByNameOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*TemplatesMetaGetByNameNotFound Template with specified identifier was not found

swagger:response templatesMetaGetByNameNotFound
*/
type TemplatesMetaGetByNameNotFound struct {

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewTemplatesMetaGetByNameNotFound creates TemplatesMetaGetByNameNotFound with default headers values
func NewTemplatesMetaGetByNameNotFound() *TemplatesMetaGetByNameNotFound {
	return &TemplatesMetaGetByNameNotFound{}
}

// WithPayload adds the payload to the templates meta get by name not found response
func (o *TemplatesMetaGetByNameNotFound) WithPayload(payload *models.Error) *TemplatesMetaGetByNameNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the templates meta get by name not found response
func (o *TemplatesMetaGetByNameNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *TemplatesMetaGetByNameNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*TemplatesMetaGetByNameDefault Unexpected error

swagger:response templatesMetaGetByNameDefault
*/
type TemplatesMetaGetByNameDefault struct {
	_statusCode int

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewTemplatesMetaGetByNameDefault creates TemplatesMetaGetByNameDefault with default headers values
func NewTemplatesMetaGetByNameDefault(code int) *TemplatesMetaGetByNameDefault {
	if code <= 0 {
		code = 500
	}

	return &TemplatesMetaGetByNameDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the templates meta get by name default response
func (o *TemplatesMetaGetByNameDefault) WithStatusCode(code int) *TemplatesMetaGetByNameDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the templates meta get by name default response
func (o *TemplatesMetaGetByNameDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the templates meta get by name default response
func (o *TemplatesMetaGetByNameDefault) WithPayload(payload *models.Error) *TemplatesMetaGetByNameDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the templates meta get by name default response
func (o *TemplatesMetaGetByNameDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *TemplatesMetaGetByNameDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
