package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/RackHD/neighborhood-manager/swagger/models"
)

// NewWorkflowsPostParams creates a new WorkflowsPostParams object
// with the default values initialized.
func NewWorkflowsPostParams() WorkflowsPostParams {
	var ()
	return WorkflowsPostParams{}
}

// WorkflowsPostParams contains all the bound params for the workflows post operation
// typically these are obtained from a http.Request
//
// swagger:parameters workflowsPost
type WorkflowsPostParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*The body must contain the name property with the value set to the injectable name of the workflow graph to run

	  In: body
	*/
	Body *models.PostWorkflow
	/*Optionally specify the injectable name of the workflow graph to run
	  In: query
	*/
	Name *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *WorkflowsPostParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.PostWorkflow
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("body", "body", "", err))
		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Body = &body
			}
		}

	}

	qName, qhkName, _ := qs.GetOK("name")
	if err := o.bindName(qName, qhkName, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *WorkflowsPostParams) bindName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.Name = &raw

	return nil
}
