package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/RackHD/neighborhood-manager/swagger/models"
)

/*WorkflowsPutTaskCreated Successfully updated workflow task

swagger:response workflowsPutTaskCreated
*/
type WorkflowsPutTaskCreated struct {

	// In: body
	Payload WorkflowsPutTaskCreatedBody `json:"body,omitempty"`
}

// NewWorkflowsPutTaskCreated creates WorkflowsPutTaskCreated with default headers values
func NewWorkflowsPutTaskCreated() *WorkflowsPutTaskCreated {
	return &WorkflowsPutTaskCreated{}
}

// WithPayload adds the payload to the workflows put task created response
func (o *WorkflowsPutTaskCreated) WithPayload(payload WorkflowsPutTaskCreatedBody) *WorkflowsPutTaskCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the workflows put task created response
func (o *WorkflowsPutTaskCreated) SetPayload(payload WorkflowsPutTaskCreatedBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *WorkflowsPutTaskCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*WorkflowsPutTaskInternalServerError Put workflow task failed

swagger:response workflowsPutTaskInternalServerError
*/
type WorkflowsPutTaskInternalServerError struct {

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewWorkflowsPutTaskInternalServerError creates WorkflowsPutTaskInternalServerError with default headers values
func NewWorkflowsPutTaskInternalServerError() *WorkflowsPutTaskInternalServerError {
	return &WorkflowsPutTaskInternalServerError{}
}

// WithPayload adds the payload to the workflows put task internal server error response
func (o *WorkflowsPutTaskInternalServerError) WithPayload(payload *models.Error) *WorkflowsPutTaskInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the workflows put task internal server error response
func (o *WorkflowsPutTaskInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *WorkflowsPutTaskInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*WorkflowsPutTaskDefault Upload failed

swagger:response workflowsPutTaskDefault
*/
type WorkflowsPutTaskDefault struct {
	_statusCode int

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewWorkflowsPutTaskDefault creates WorkflowsPutTaskDefault with default headers values
func NewWorkflowsPutTaskDefault(code int) *WorkflowsPutTaskDefault {
	if code <= 0 {
		code = 500
	}

	return &WorkflowsPutTaskDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the workflows put task default response
func (o *WorkflowsPutTaskDefault) WithStatusCode(code int) *WorkflowsPutTaskDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the workflows put task default response
func (o *WorkflowsPutTaskDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the workflows put task default response
func (o *WorkflowsPutTaskDefault) WithPayload(payload *models.Error) *WorkflowsPutTaskDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the workflows put task default response
func (o *WorkflowsPutTaskDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *WorkflowsPutTaskDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
